feat: hassuyp 213
finnishtransportagency/hassu pull request #1030
Opened 2023-11-27 13:49 UTC by ValheKouneli

MuuAineisto ja LisaAineistot onkin LadattuTiedosto-tyyppiä. Löytyi kai myös samalla bugeja TiedostoManagerista. Testit on työllä ja tuskalla päivitetty vastaamaan uutta speksiä. Voi olla ettei niiden osalta kannata katsoa muutoslogeja vaan ihan vaan itse testejä...

2023-11-30 07:14 UTC, hakalap commented on deployment/lib/hassu-backend.ts
> +          actions: ["cloudfront:CreateInvalidation", "ssm:GetParameter"],
Lisää uusi PolicyStament jossa resources *, vaikka ennen tätä if:ä.

2023-12-05 12:37 UTC, hakalap requested changes

2023-12-05 12:37 UTC, hakalap commented on src/components/projekti/lausuntopyynnot/LausuntoPyynnonTaydennysForm/LausuntoPyynnonTaydennysPainikkeet.tsx
> +      const tallennaProjektiInput: TallennaProjektiInput = mapLausuntoPyynnonTaydennysFormValuesToLausuntoPyyntoInput(formData);
Tämä varmaan pitäisi muodostaa LausuntopyynnonTaydennysInput. Ainakaan nyt se täydennyksen tallennus ei toimi.

2023-12-05 12:37 UTC, hakalap commented on src/components/projekti/lausuntopyynnot/Linkki.tsx
> +            localStorage.setItem(`lausuntoPyyntoInput.${uuid}`, JSON.stringify(adaptedInput));
Nämä olisi hyvä poistaa localStoragesta kun esim. esikatselutabi suljetaan.

2023-12-08 08:47 UTC, ValheKouneli commented on src/components/projekti/lausuntopyynnot/Linkki.tsx
> +            localStorage.setItem(`lausuntoPyyntoInput.${uuid}`, JSON.stringify(adaptedInput));
done

2023-12-08 08:48 UTC, ValheKouneli commented on deployment/lib/hassu-backend.ts
> +          actions: ["cloudfront:CreateInvalidation", "ssm:GetParameter"],
done

2023-12-13 12:22 UTC, closed without merging