Feature/hassuyp 205 saavutettavuus
finnishtransportagency/hassu pull request #1061
Opened 2024-01-08 11:11 UTC by mustonenk

2024-01-10 12:57 UTC, tkork commented on src/components/layout/footer.tsx
> +            s
Tämä tainnut tulla vahingossa?

2024-01-10 13:02 UTC, tkork commented on src/components/layout/footer.tsx
> +                  <Image src="/ely_alla_fi_sv_rgb.png" alt="" width="170.61" height="91" />
Miksi nämä altit poistettu? Yhdessä commitissa asetit altit tyhjiksi stringeiksi ja toisessa poistit ne. Miten nämä on redundantteja?

2024-01-10 13:04 UTC, tkork requested changes
Laitan nyt tähän request changes. Se lisätty s-kirjain on varmastikin vahingossa tullut, mutta ihmettelen myös miksi ne altit oli turhia. Tietty ne altit oli ainakin sen jälkeen turhia kun ne asetettiin tyhjiksi stringeiksi. Ja edelleenhän ne on tyhjiä stringejä. Eikös koko attribuutti kannata poistaa, jos sille annetaan tyhjä stringi arvoksi.

2024-01-10 13:08 UTC, tkork commented on src/components/notification/Notification.tsx
> +    const { t, lang } = useTranslation("common");
Lang-muuttujaa ei käytetä. Buildikin tästä valittaa

2024-01-10 14:44 UTC, mustonenk commented on src/components/layout/footer.tsx
> +            s
joo

2024-01-10 14:54 UTC, mustonenk commented on src/components/notification/Notification.tsx
> +    const { t, lang } = useTranslation("common");
korjattu

2024-01-11 07:06 UTC, tkork approved these changes

2024-01-11 07:11 UTC, merged