feat: hassuyp 319
finnishtransportagency/hassu pull request #1074
Opened 2024-01-25 12:27 UTC by ValheKouneli

2024-01-29 13:14 UTC, tkork commented on backend/src/projekti/validator/validateHyvaksymisEsitys.ts
> +    }
Inputin GraphQL tyypitys kyllä estää jo väärien avaimien pääsyn, että sinänsä tää hyväksyttyjen avaimien validointi on ehkä vähä tarpeetonta. Noissa testeissähän tää tietty tekee jotain kun GraphQL schemaa ei samalla tavalla pelitä.

2024-01-29 13:19 UTC, tkork commented on backend/src/handler/tiedostoDownloadLinkHandler.ts
> +    if (!hyvaksymisEsitys) {
Pitäskö tarkistaa, et käyttäjällä on muokkausoikeus projektiin?

2024-01-29 13:24 UTC, tkork commented on graphql/types.graphql
> +  kunta: Int
Tekisin kyl oman tyypin näille (HyvaksymisEsitysLadattuTiedosto), jottei toi kunta olis kenttänä jokaisessa ladatussa tiedostossa. Mielestäni on aika eri asia, että jokaisella tiedostolla on järjestyskenttä vaikkei sitä (toistaiseksi) käytettäisi jokasessa käyttöpaikassa. Järjestys nyt on aika geneerinen tieto kun sitten tämä kuntatieto on hyvin spesifi tieto, joka enemmänkin kummaksuttaa tullessaan rajapinnasta tiedostoihin, joissa sitä ei tarvita.

2024-01-29 13:32 UTC, tkork requested changes
Laittaisin erillisen tyypityksen niille hyvaksymisesityksen tiedostoille. En järin pidä siitä, että kaikille aiemmille ladatuille tiedostoille tulee tyypitykseen niille täysin epäolennainen kuntatieto. Onko siinä ongelmaa, jos laittaisi graphql:ssä interfacen ILadattuTiedosto, jota implementoidaan LadattuTiedosto ja HyvaksymisEsitysLadattuTiedosto tyypeissä? Tällaisia interface-tyyppi jatkoksia on graphql schemassamme jo muutamia. Jos ymmärrän oikein, pari adaptointi funktiota joutuisi tekemään enemmän, mutten nää että työ olisi hirveän iso.

2024-03-12 10:43 UTC, kettunju commented
jatketaan toisessa pr:ssä

2024-03-12 10:43 UTC, closed without merging