feat: hassuyp 406 linkin esikatselu
finnishtransportagency/hassu pull request #1169
Opened 2024-05-22 13:17 UTC by ValheKouneli

Pitäis olla esikatselussa kaikki kunnossa, ja ulkoasukin margineideen about speksin mukainen. Toki suunnitelman katsomista ei oikein voi testata, ellei jaksa feikata dataa käsin DB:hen.

2024-05-22 13:18 UTC, ValheKouneli commented on backend/integrationtest/HyvaksymisEsitys/esikatseleTiedostot.test.ts
>    const oid = "Testi1";
Nää oli relevantteja vain yhden testin kannalta, ni siirsin ne siihen testiin.

2024-05-22 13:18 UTC, ValheKouneli commented on backend/integrationtest/HyvaksymisEsitys/esikatseleTiedostot.test.ts
>          .filter((nimi) => !nimi.includes("hyvaksymisEsitys"))
Muutosten myötä saametiedostot ei tullut enää tonne. Ei pidäkään tulla.

2024-05-22 13:19 UTC, ValheKouneli commented on backend/integrationtest/HyvaksymisEsitys/listaaTiedostot.test.ts
>      });
Loin tosiaan ihan oman tyypin tuolle hyväksymisesityksen ladattavien tiedostojen kokonaisuudelle.

2024-05-22 13:19 UTC, ValheKouneli commented on backend/src/HyvaksymisEsitys/actions/listaaTiedostot.ts
>  }
Noi lisätiedot, kuten asiatunnus jne., oli päässyt unohtumaan tästä datasta. Nyt lisätty.

2024-05-22 13:20 UTC, ValheKouneli commented on backend/src/HyvaksymisEsitys/latauslinkit/createLadattavatTiedostot.ts
Ajattelin, että tässä funktiossa keskitytään keräämään kaikki noi ladattavat tiedostot, ja sit funktion ulkopuolella laitetaan ne lisädatat.

2024-05-22 13:21 UTC, ValheKouneli commented on backend/src/HyvaksymisEsitys/latauslinkit/createLadattavatTiedostot.ts
>    }
Tää hajos aiemmin, koska vaikka projekti ei olis saameprojekti, ni sille tulee aloituskuulutusSaamePDFt.POHJOISSAAME = {}.

2024-05-22 13:21 UTC, ValheKouneli commented on graphql/types.graphql
>    muistutukset: [LadattavaTiedosto!]
Poistin LadattavatTiedostot-tyypistä ne kentät, mitkä siellä oli vain hyväksymisesityksen takia.

2024-05-22 13:23 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/AineistonEsikatselu.tsx
Tää toimii samalla logiikalla kuin lausuntopyyntöjen esikatselu, eli kun nappia painaa, lomakkeen sisältö tallennetaan localStorageen. Sit ohjataan esikatselusivulle. Esikatselusivu kaivaa lomakkeen datan localStoragesta ja laittaa sen esikatselun api-kutsun inputiin. Vois kai tän tehdä sellaikin, että pysytään vaan samalla sivulla, mut mennään eri näkymään, tms., mutta nyt näin.

2024-05-22 13:24 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/LinkkiHyvEsAineistoon.tsx
Täältä poistui se esikatselunappi. Se siirtyi eri paikkaan.

2024-05-22 13:24 UTC, ValheKouneli commented on src/components/LadattavatTiedostot/SuunnitelmaAccordion.tsx
Tää SuunnitelmaAccordion on käytössä lausuntopyynnöissä myös. Siirsin sen sieltä omaan paikkaansa, niin sitä voi käyttää hyväksymisesityksen aineistonäkymässä.

2024-05-22 13:25 UTC, ValheKouneli commented on src/components/projekti/lausuntopyynnot/LausuntopyyntoAineistoPage.tsx
>          {aineistot?.length && <H2>Suunnitelma</H2>}
Tää on vain uudelleennimeäminen.

2024-05-22 13:25 UTC, ValheKouneli commented on src/components/projekti/lausuntopyynnot/LausuntopyyntoTaydennysAineistoPage.tsx
Siirsin tämän eri paikkaan. Siksi import päivittyi.

2024-05-22 13:26 UTC, ValheKouneli commented on src/hooks/useEsikatseleHyvaksymisEsitys.tsx
Tämä hook hakee esikatselussa tapahtuvan api-kutsun.

2024-05-22 13:26 UTC, ValheKouneli commented on src/pages/yllapito/projekti/[oid]/esikatsele-hyvaksymisesitys.tsx
Tää sivu on tarkoitus laittaa myöhemmin eri osoitteen taakse, mutta saa nyt olla tää. Myöhemmin [oid]/hyvaksymisesitys/esikatselu

2024-05-22 13:29 UTC, ValheKouneli commented on backend/integrationtest/HyvaksymisEsitys/TEST_PROJEKTI.ts
Lisäsin testiprojektiin kenttiä, jotta voin hyv.es. linkin esikatselussa testata, tuleehan projektille oikeat datat, esim. nimi ja projarin tiedot.

2024-05-23 13:37 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/AineistoPage.tsx
> +
Tässä sortataan muistutukset kunnan mukaan.

2024-05-23 13:39 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/LinkkiHyvEsAineistoon.tsx
Hyväksymisesityksen UI-kuvissa esikatselu-nappi oli eri kohdassa kuin "kopioi linkki" -nappi. Siksi se siirrettiin tästä pois.

2024-05-23 13:40 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/getDefaultValuesForForm.ts
>    };
Tää oli aiemmin väärin

2024-05-23 13:40 UTC, ValheKouneli commented on src/components/LadattavatTiedostot/LadattavaTiedosto.tsx
>      return (
Muutos:
Tiedosto (png 1.2.2014) -> Tiedosto (png) 1.2.2014

2024-05-23 13:41 UTC, ValheKouneli commented on src/components/LadattavatTiedostot/SuunnitelmaAccordion.tsx
Siirsin tämän toisesta paikasta ja nimesin geneerisemmin.

2024-05-23 13:47 UTC, ValheKouneli commented on src/components/LadattavatTiedostot/SuunnitelmaAccordion.tsx
Siirsin tämän toisesta paikasta ja nimesin geneerisemmin.

2024-05-24 10:41 UTC, tkork requested changes
Haitareihin vois laittaa jotain sisältöä jos näytettävä lista on tyhjä (esim. "Ei aineistoa" tai vastaavaa). Katsoisitko myös muut kommentit.

2024-05-24 10:41 UTC, tkork commented on src/components/HyvaksymisEsitys/AineistoPage.tsx
> +          </HassuGrid>
Kaikkin tietoihin, jotka voi olla tyhjää olis varmaa parempi laittaa toi fallback arvona toi "-"

2024-05-24 10:41 UTC, tkork commented on src/components/HyvaksymisEsitys/AineistoPage.tsx
> +        </SectionContent>
Halutaanko tätä osioa/otsikkoa näyttää, jos lisatiedot on undefined|null|""?

2024-05-24 10:41 UTC, tkork commented on src/components/HyvaksymisEsitys/AineistoPage.tsx
> +              <p>{vastuuorganisaatio}</p>
"Käännä" tää vastuuorganisaatio suomenkieliseks niin ei tuu "VAYLAVIRASTO"-enum arvoa näytille

2024-05-27 11:32 UTC, tkork commented on src/components/HyvaksymisEsitys/AineistoPage.tsx
> +            </HassuGridItem>
Tässä ei toimi toi nullish coalescing -operaattori (eli ??), koska t("...") palauttaa aina jonku stringin. Palauttelee ton avaimen, jos arvoa ei ole.

2024-05-27 11:38 UTC, tkork approved these changes

2024-05-27 11:38 UTC, merged