feat: HASSUYP-402 Asettelu ja tyylit hyväksymisesityksen lomakkeelle
finnishtransportagency/hassu pull request #1177
Opened 2024-05-29 08:25 UTC by tkork

2024-05-29 09:59 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/HyvaksymisEsitysLomake.tsx
> +                    vastaanottajat. Järjestelmä luo ja lähettää vastaanottajille automaattisesti sähköpostiviestin, jonka linkkistä pääsee
linkkistä -> linkistä

2024-05-29 10:03 UTC, tkork commented on src/components/HyvaksymisEsitys/HyvaksymisEsitysLomake.tsx
> +                    vastaanottajat. Järjestelmä luo ja lähettää vastaanottajille automaattisesti sähköpostiviestin, jonka linkkistä pääsee
Joo. Aivan kopypastevirhettä sketsistä. Mä tarkistan viel conflusta muutenkin oliko jotain tekstipoikkeamia.

2024-05-29 10:20 UTC, ValheKouneli approved these changes
Rebase vielä ja näytä projektin tiedot laskutustietojen yhteydessä oikein.

2024-05-29 10:29 UTC, ValheKouneli requested changes
- poistetaan y-tunnus LaskutustiedotInputista ja Laskutustietoista
- siirretään y-tunnus HyväksymisEsityksen yhteydessä palautettaviin ProjektinPerustietoihin
- siirretään BE:ssä getAsiatunnus vai olikose adaptAsiatunnus johkin eri paikkaan kuin velhoadapteriin
- kun Hyväksymisesityksen tietoja haetaan ja annetaan projektin perustiedot, käytetään siinä yhteydessä getAsiatunnus-funktiota, jotta voidaan antaa oikea asiatunnus
- FE:ssä näytetään projektin perustiedot + asiatunnus, eli kovakoodaukset pois
- lisätään myös kunnat perustietoihin, jotta osataan näyttää oikeat kunnat UI:ssa. Korjataan tää kuntahomma ja asiatunnus-homma myös lukutilaiseen ja esikatseluun

2024-05-30 10:02 UTC, ValheKouneli requested changes
Ihan pikkumuutoksia enää

2024-05-30 10:08 UTC, tkork commented on backend/src/velho/velhoAdapter.ts
>    return metaDataJSON;
Lintteri noist valitti. Muokkasin koodia, mutten koskenut logiikkaan sinänsä tossa lainkaan. Ajatus oli, että olisin ottanut sen asiatunnuksen päättelyjutun tuolta tiedostosta erilleen, mutta se ei ollut täysin samaa niin en ottanut muokannut siihen liittyen velhoAdapterissa mitään. 

Tämän muutoksen jätin tänne, koska vähensi lintterien havaitsemia ongelmia.

2024-05-30 10:08 UTC, tkork commented on backend/src/util/vastaavaViranomainen/asiatunnus.ts
> +
Voin sen löyhentää.

2024-05-30 10:09 UTC, tkork commented on backend/src/HyvaksymisEsitys/actions/haePerustiedot.ts
Joo voin siirtää ton. Miksi nimeksi formPerustiedot? Siksikö, että tämä muodostaa perustiedot? Mielestäni huono nimi, koska form termiä käytetään lomakkeissa.

2024-05-30 10:14 UTC, ValheKouneli commented on backend/src/HyvaksymisEsitys/actions/haePerustiedot.ts
Pointti. Jotain muuta kuitenkin kuin "hae", koska he kuulostaa siltä että haetaan DB:stä. get voisi olla. format olis mahdollinen.

2024-05-30 10:19 UTC, tkork commented on backend/src/velho/velhoAdapter.ts
>    return metaDataJSON;
Yleisesti siis olen tykännyt korjata lintterihavaintoja tiedostoista joihin kosken, vaikkei muutokset suoranaisesti toteutusta koskisi. Tietty kannattaa olla varma, ettei muuta logiikkaa ainakaan liiaksi ettei tule odottamattomia muutoksia.

Tässä koskin oikeastaan koodin typescript tyypitykseen ja ajattelemattomasti tehtyyn Array.prototype.forEachiin asetettuun callback-funktioon, joka oltiin kummasti ja virheellisesti laitettu palauttamaan expressioni

2024-05-30 10:29 UTC, tkork commented on backend/src/HyvaksymisEsitys/actions/haePerustiedot.ts
Teen nimeämisen siihen tyyliin mitä yhdessä keskusteltiin. Siirretään hyväksymispäätöksen adaptereihin ja uudelleennimeäminen sen mukaiseksi.

2024-05-30 11:08 UTC, ValheKouneli approved these changes

2024-05-30 11:09 UTC, merged