feat: hassuyp 405 linkin katselu
finnishtransportagency/hassu pull request #1179
Opened 2024-05-30 10:53 UTC by ValheKouneli

Linkin katselun pitäisi toimia. Jos linkki on voimassa ja jokin hyväksymisesitys on julkaistu, linkin takana pitäisi näkyä oikeat jutut. Jos linkki on vanhentunut, pitäisi näkyä teksti, joka kertoo siitä. Kun linkki on voimassa ja avaa tiedostoja, niiden tulisi kaikkien aueta. Toki vielä ei voi testata, että aineistotkin aukeaa, mutta esim. automaattisesti tuodut pdf:t ja maanomistajaluettelo pitäisi toimia.

2024-05-30 10:54 UTC, ValheKouneli commented on backend/integrationtest/HyvaksymisEsitys/listaaTiedostot.test.ts
>      // Testataan, saadaanko uudet tiedostot
Koska aineistoHandledAt puuttui näistä, BE:n testit ei saanut kiinni yhtä bugia, minkä korjasin tuossa alla.

2024-05-30 10:55 UTC, ValheKouneli commented on backend/src/HyvaksymisEsitys/latauslinkit/createLadattavatTiedostot.ts
>    const hyvaksymisEsitysTiedostot: API.LadattavaTiedosto[] = (
Tää logiikka jäi virheelliseksi sen jälkeen kun siirsin aineistoHandledAt olemaan projektin ylätasossa eikä muokattavanHyvaksymisEsityksen sisällä.

2024-05-30 10:55 UTC, ValheKouneli commented on common/abstractApi.ts
Tässä oli vähää parametrin nimi, minkä vuoksi se ei olisi ilman tätä muutosta toiminut.

2024-05-30 10:56 UTC, ValheKouneli commented on src/components/projekti/lausuntopyynnot/VanhentunutAineistolinkki.tsx
>            Aineistoon liittyvissä tiedusteluissa ja kysymyksissä voit olla yhteydessä projektipäällikköön. Voit pyytää esimerkiksi jatkoa
Otin tän komponentin käyttöön myös hyväksymisesityksen tapauksessa. Pitäisikö tämä siirtää eri kohtaan kansiorakennetta..?

2024-05-30 10:56 UTC, ValheKouneli commented on src/locales/sv/breadcrumbs.json
>    }
En tiiä mitä tää on ruotsiksi...

2024-05-30 13:13 UTC, tkork commented on src/pages/suunnitelma/[oid]/lausuntopyyntoaineistot.tsx
> +    return <VanhentunutAineistolinkki suunnitelmanNimi={projekti.velho?.nimi!} data={data} />;
Ei oo hyvä käyttää näitä huutomerkkejä. Ennemmin sit löyhentää tyyppiehtoja niin et hyväksyy undefinedin ja käsittelee sen tuolla VanhentunutAineistolinkki-komponentissa.

2024-05-30 13:14 UTC, tkork commented on src/pages/suunnitelma/[oid]/lausuntopyynnon-taydennysaineistot.tsx
> +    return <VanhentunutAineistolinkki suunnitelmanNimi={projekti.velho?.nimi!} data={data} />;
Käsittele jollai muulla tavalla kuin tolla huutomerkillä

2024-05-30 13:14 UTC, tkork commented on src/pages/suunnitelma/[oid]/hyvaksymisesitys.tsx
> +  }
rebasen jälkeen tää pitää päivittää data.perustiedot.suunnitelmanNimi

2024-05-30 13:19 UTC, tkork commented on src/components/projekti/lausuntopyynnot/VanhentunutAineistolinkki.tsx
>            Aineistoon liittyvissä tiedusteluissa ja kysymyksissä voit olla yhteydessä projektipäällikköön. Voit pyytää esimerkiksi jatkoa
Joo ehkä sille olis perusteita joku _aineisto_ kansio vois olla aiheellinen. src/components/projekti/common/Aineistot alle? Ihmettelen et kansionimi isolla...

2024-05-30 13:21 UTC, tkork commented on src/locales/sv/breadcrumbs.json
>    }
Oliskohan se parempi kysästä ja hommaa joku käännös vai annettasko mennä vaa suomenkielisenä, koska ei tätä oo tarkotus kattoa edes ruottiksi ja on suunntattu vaan virkamiehille.

2024-05-30 13:22 UTC, tkork requested changes
Rebasen myötä tuli jotain pientä korjattavaa ja muutakin pientä tos oli. ks kommentit

2024-05-31 12:25 UTC, tkork approved these changes

2024-06-03 09:09 UTC, merged