feat: hassuyp 399 muistutukset taulukko
finnishtransportagency/hassu pull request #1217
Opened 2024-06-19 10:20 UTC by ValheKouneli

2024-06-19 10:22 UTC, ValheKouneli commented on backend/src/HyvaksymisEsitys/actions/tallenna.ts
TestiType siirtyi commoniin

2024-06-19 10:23 UTC, ValheKouneli commented on backend/src/HyvaksymisEsitys/actions/tallennaJaLahetaHyvaksyttavaksi.ts
TestType siirtyi commoniin

2024-06-19 10:23 UTC, ValheKouneli commented on common/schema/common.ts
TestType siirtyi hyväksymniseistysSchemasta tänne commoniin. Loin myös uudet funktion isTestTypeFrontend ja isTestTypeBackend. Niitä käytetään hyväksymisesityksSchemassa ja jatkossa mahdollisesti muuallakin.

2024-06-19 10:25 UTC, ValheKouneli commented on common/schema/hyvaksymisEsitysSchema.ts
HyväksymisEsitysSchemassa muistutukset validoidaan nyt FE:ssä eri tavalla, koska muistutuksen tyyppi hyväksymisesityksen form datassa muuttui. Backendissä muistutukset validoidaan kuitenkin BE-tyypin mukaan, joka on sama kuin ennen.

2024-06-19 10:26 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/HyvaksymisEsitysLomake.tsx
FormDatan tyyppi muuttui. Se on nyt eri kuin Input-datan tyyppi. Se on lomakkeelle oma.

2024-06-19 10:26 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/AineistonEsikatselu.tsx
FormDatan tyyppi muuttui. Se on nyt eri kuin Input-datan tyyppi. Se on lomakkeelle oma.

2024-06-19 10:26 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/HyvaksymisEsitysTiedosto.tsx
FormDatan tyyppi muuttui. Se on nyt eri kuin Input-datan tyyppi. Se on lomakkeelle oma.

2024-06-19 10:26 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/KuulutuksetJaKutsu.tsx
FormDatan tyyppi muuttui. Se on nyt eri kuin Input-datan tyyppi. Se on lomakkeelle oma.

2024-06-19 10:26 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/Laskutustiedot.tsx
FormDatan tyyppi muuttui. Se on nyt eri kuin Input-datan tyyppi. Se on lomakkeelle oma.

2024-06-19 10:26 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/Lausunnot.tsx
FormDatan tyyppi muuttui. Se on nyt eri kuin Input-datan tyyppi. Se on lomakkeelle oma.

2024-06-19 10:27 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/MaanomistajaLuettelo.tsx
FormDatan tyyppi muuttui. Se on nyt eri kuin Input-datan tyyppi. Se on lomakkeelle oma.

2024-06-19 10:30 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/Muistutukset.tsx
Muistutusten lomakekomponentti muuttui radikaalisti, koska muistutukset näytetään nyt tiedostotaulukkoa käyttäen. Sille on injektoitava tieto db:ssä olevista muistutuksista, jotta se osaa näyttää muistutuksille lomakedatasta puuttuvan lisätty-aikaleiman.

2024-06-19 10:31 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/MuokkausLomakePainikkeet.tsx
vanha adaptFormDataForAPI-funktio, joka ei tehnyt oikeasti mitään adaptointia, on nyt muutettu hyvaksymisEsitysFormUtilista importoidulla tranformaatiofunktiolla, joka huolehtii muistutusten tranformoimisesta form-muodosta input-muotoon.

2024-06-19 10:32 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/MuuAineistoKoneelta.tsx
FormDatan tyyppi muuttui. Se on nyt eri kuin Input-datan tyyppi. Se on lomakkeelle oma.

2024-06-19 10:32 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/MuuAineistoVelhosta.tsx
FormDatan tyyppi muuttui. Se on nyt eri kuin Input-datan tyyppi. Se on lomakkeelle oma.

2024-06-19 10:32 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/Suunnitelma.tsx
FormDatan tyyppi muuttui. Se on nyt eri kuin Input-datan tyyppi. Se on lomakkeelle oma.

2024-06-19 10:32 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/Vastaanottajat.tsx
FormDatan tyyppi muuttui. Se on nyt eri kuin Input-datan tyyppi. Se on lomakkeelle oma.

2024-06-19 10:32 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/LomakeComponents/ViestiVastaanottajalle.tsx
FormDatan tyyppi muuttui. Se on nyt eri kuin Input-datan tyyppi. Se on lomakkeelle oma.

2024-06-19 10:34 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/hyvaksymisEsitysFormUtil.ts
getDefaultValuesForForm-tiedosto muuttui hyvaksymisEsitysFormUtil-tiedostoksi, joka sisältää getDefaultValues-funktion lisäksi myös hyväksymisesitys-formin tyypityksen ja transformaatiofunktion form-datasta input-dataan.

getDefaultValues-funktiota on päivitetty ottamaan huomioon uusi form datan tyypitys.

2024-06-24 12:42 UTC, tkork requested changes

2024-06-24 12:42 UTC, tkork commented on src/components/HyvaksymisEsitys/hyvaksymisEsitysFormUtil.ts
> +        : [],
oisko tää parempi

muistutukset: muistutukset ? Object.values(muistutukset).filter((m): m is KunnallinenLadattuTiedostoInput[] => !!m).flat() : null,

2024-06-24 12:42 UTC, tkork commented on src/components/HyvaksymisEsitys/hyvaksymisEsitysFormUtil.ts
> +export function transformHyvaksymisEsitysFormToTallennaHyvaksymisEsitysInput(formData: HyvaksymisEsitysForm) {
Laittasin tälle funktiolle explisiittisen palautustyypin

2024-06-24 12:50 UTC, tkork approved these changes

2024-06-25 11:47 UTC, merged