fix: HASSUYP-329 Hyväksymisesityksen operaatioiden estäminen jos vaihe on liian varhainen
finnishtransportagency/hassu pull request #1223
Opened 2024-06-20 10:33 UTC by tkork

2024-06-26 12:11 UTC, ValheKouneli commented on backend/src/HyvaksymisEsitys/actions/tallenna.ts
> +  await validateVaiheOnAktiivinen(projektiInDB);
Tämä validaatio on kaikista raskain, niin sen voisi kenties laittaa ihan loppuun. Ei sillä oikeasti tosin siis kauheasti väliä ole.

Koska muissa validaatioissa on kommentti, tätäkin ennen voisi laittaa kommentin.

2024-06-26 12:40 UTC, tkork commented on backend/src/HyvaksymisEsitys/vaiheOnAktiivinen.ts
Se on käytössä muuallakin. haeTiedot-toteutuksessa kutsutaan vaiheOnAktiivinen-tietoa.

2024-06-26 12:55 UTC, tkork commented on backend/src/HyvaksymisEsitys/actions/tallenna.ts
> +  await validateVaiheOnAktiivinen(projektiInDB);
Voin siirtää ne

2024-06-26 14:02 UTC, ValheKouneli requested changes
Muokkaa-nappi näkyy UI:ssa, vaikkei se enää toimisi.

Lisäksi voisi korjata samassa PR:ään liittymättömän ongelman, eli AineistonEsikatselu.tsx-komponentissa

```
          localStorage.setItem(
           `tallennaHyvaksymisEsitysInput`,
            JSON.stringify(transformHyvaksymisEsitysFormToTallennaHyvaksymisEsitysInput(formData))
          );
```

2024-06-27 13:34 UTC, ValheKouneli approved these changes

2024-06-28 07:50 UTC, merged