feat: hassuyp 414 aineisto zip
finnishtransportagency/hassu pull request #1226
Opened 2024-06-25 11:17 UTC by ValheKouneli

Aineistojen zippaus. Myös pieniä korjauksia.

2024-06-25 11:18 UTC, ValheKouneli commented on backend/integrationtest/HyvaksymisEsitys/TEST_HYVAKSYMISESITYS.ts
Tää piti muuttaa, koska kuntametadatassa ei oo kuntaa id:llä 1, ja zippaushommissa tarvitaan kunnan nimitietoa.

2024-06-25 11:18 UTC, ValheKouneli commented on backend/integrationtest/HyvaksymisEsitys/adaptHyvaksymisEsitysToAPI.test.ts
muutin adaptToAPI:ia siten, että zip-tiedoston koko polku tulee fronttiin, eli toimii kuten tiedostot/aineistot

2024-06-25 11:20 UTC, ValheKouneli commented on backend/src/HyvaksymisEsitys/actions/tallennaJaLahetaHyvaksyttavaksi.ts
>      throw new IllegalArgumentError("Aineistojen on oltava valmiita ennen kuin hyväksymisesitys lähetetään hyväksyttäväksi.");
Korjasin logiikan tässä. En luottanut tuohon localeCompareen, niin korvasin sen. Koetin ensin parseDatea, mutta se ei toiminut, niin laitoin ton dayjs:n.

2024-06-25 11:22 UTC, ValheKouneli commented on backend/src/HyvaksymisEsitys/aineistoHandling/haeZipTiedostot.ts
Tässä koodissa on paljon samaa kuin getLadatutTiedostot-koodissa, mutta en nyt lähtenyt monimutkaistamaan tekemällä jotain yhdistävää funktiota.

2024-06-25 11:23 UTC, ValheKouneli commented on backend/src/tiedostot/zipFiles.ts
Tässä olen koskenut "vanhaan koodiin". Tää tekee kuitenkin ihan saman asian. Pointti oli, että aiemmat tätä käyttävät funktiot luotti siihen, että zipFolder-string päättyy kauttamerkkiin. Nyt se voi joko päättyä siihen tai olla päättymättä. JoinPath-pitää huolen siitä, että kauttamerkki tulee polkuun oikein.

2024-06-25 11:24 UTC, ValheKouneli commented on src/components/HyvaksymisEsitys/HyvaksymisEsitysLukutila.tsx
>        <Section>
Koin että tämä on hyvä olla, koska aineisto-zip ei välttämättä ole valmis heti kun hyv.es. on hyväksyttävänä. Sketch-kuvissa ei tätä ole.

2024-06-25 13:33 UTC, hakalap requested changes

2024-06-25 13:33 UTC, hakalap commented on backend/src/HyvaksymisEsitys/aineistoHandling/haeZipTiedostot.ts
> +          s3Key: joinPath(getYllapitoPathForProjekti(projekti.oid), nahtavillaoloVaiheJulkaisu.maanomistajaluettelo),
Tämä väärin. Maanomistajaluettelo sisaiset kansiossa. Zippaus kaatuu tähän.

2024-06-26 09:33 UTC, ValheKouneli commented on backend/integrationtest/HyvaksymisEsitys/TEST_HYVAKSYMISESITYS.ts
Kunta id 1 ei ole olemassa

2024-06-26 09:33 UTC, ValheKouneli commented on backend/integrationtest/HyvaksymisEsitys/TEST_PROJEKTI.ts
tila-tietoja tarvii joissain testeissä

2024-06-26 09:35 UTC, ValheKouneli commented on backend/src/HyvaksymisEsitys/actions/haeTiedot.ts
Tein linkin katselulle ja zippaukselle yhteisiä funkkareita, joilla haetaan noita olennaisia tiedostoja. Ks. collectHyvaksymisEsitysAineisto.ts

2024-06-26 09:35 UTC, ValheKouneli commented on backend/src/HyvaksymisEsitys/actions/listaaTiedostot.ts
Aineistopaketti meneekin nyt DBProjektin ylimmälle tasolle, koska muuten tulee ongelmia aineistolambdan ja BE:n rinnakkaisen suorituksen kanssa.

2024-06-26 11:09 UTC, hakalap approved these changes

2024-06-26 11:52 UTC, merged