Hassuyp-122:  Virkamiehen etusivun tab korvattu Mui:n Tabilla
finnishtransportagency/hassu pull request #1248
Opened 2024-07-29 12:09 UTC by vilruus

Tiketti: [HASSUYP-122](https://extranet.vayla.fi/jira/browse/HASSUYP-122)

2024-08-01 10:17 UTC, hakalap requested changes

2024-08-01 10:17 UTC, hakalap commented on src/pages/yllapito/index.tsx
> -              fetchProjektit({ ...searchInput, projektiTyyppi: null, epaaktiivinen: true, sivunumero: 0 });
Peru tämä muutos, koska muuten epäaktiivinen tabilla näkyy kaikki projektit.

2024-08-02 11:34 UTC, vilruus commented on src/pages/yllapito/index.tsx
> -              fetchProjektit({ ...searchInput, projektiTyyppi: null, epaaktiivinen: true, sivunumero: 0 });
Peruttu

2024-08-02 11:58 UTC, hakalap approved these changes

2024-08-05 05:09 UTC, merged