feat: Tee nappulat hyväksymisvaiheen pdf:ien esikatselulle ja katselulle
finnishtransportagency/hassu pull request #345
Opened 2022-08-30 11:11 UTC by ValheKouneli

Huom! BE ei vielä generoi hyväksymisvaiheen pdf:iä. Olennaisesti sama toteutus kuin nähtävilläolossa, jossa homma pelittää, joten matala riski, että olisi jotain ongelmaa.

2022-09-01 13:05 UTC, tkork requested changes
Toi muutos hyvaksymispaatosKuulutus-schemaan ei ainakaan taida olla toivottu. Bäkkäri ei hyväksy tyhjiä stringejä.

Virkamiespuolella lukutilassa noiden PDF:ien linkeissä on enemmä välityksiä ja niissä on käytetty sitä

Toteutus:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/77731851/187918239-2a085bee-4633-40f0-9313-71d99c5f6a2e.png">

Kälikuva: 
<img width="639" alt="image" src="https://user-images.githubusercontent.com/77731851/187918588-b8bb3490-ee7d-4c7f-8714-d11f57bdbe38.png">

Yks havainto, minkä nyt tässä PR:ssä tein, vaikkei tässä PR:ssä sitä komponenttia muokattukaan... 'Hyväksy ja lähetä' -painike (ja todennäköisesti 'Palauta'-painike) submittaa html formin, eli event.preventDefaulttia ei tapahdu.

src/components/projekti/hyvaksyminen/kuulutuksenTiedot/Painikkeet.tsx

2022-09-01 13:21 UTC, ValheKouneli commented on deployment/localstack/docker-compose.yml
> +version: "3.3"
Tämä oli moka!

2022-09-02 06:06 UTC, tkork commented on src/components/form/Select.tsx
> +          {addEmptyOption && <option value="" />}
Juu tämä OK 👍

2022-09-05 06:52 UTC, tkork approved these changes

2022-09-05 06:58 UTC, merged