feat: hassu 992 haku
finnishtransportagency/hassu pull request #363
Opened 2022-09-09 13:07 UTC by ValheKouneli

Puuttuu vielä käännökset ainakin

2022-09-12 13:14 UTC, tkork requested changes
Pitikö tän jo hakea jotain. Tätä ei kannata mergee ennen ku toi lomake oikeesti hakee jotain.
Enterillä hakeminen ei täl hetkel viel toimi. Se on kyl kans yks juttu mikä varmaa tarttettais.

2022-09-13 08:58 UTC, ValheKouneli commented on src/components/kansalaisenEtusivu/Hakulomake.tsx
> +                />
Tää on myöhemmässä PR:ssä

2022-09-13 08:58 UTC, ValheKouneli commented on src/components/kansalaisenEtusivu/Hakulomake.tsx
> +                    />
Tää on myöhemmässä PR:ssä

2022-09-13 09:07 UTC, ValheKouneli commented on src/components/kansalaisenEtusivu/Hakulomake.tsx
> +                    />
Toteutan

2022-09-13 09:07 UTC, ValheKouneli commented on src/pages/index.tsx
>          <p>Tekstiä</p>
Toteutan

2022-09-13 09:12 UTC, ValheKouneli commented on src/components/kansalaisenEtusivu/Hakulomake.tsx
> +              </Button>
Heh, pointti, enpä ajatellut. Korjaan.

2022-09-13 09:42 UTC, ValheKouneli commented on i18n.js
> +    "*": ["common", "projekti", "etusivu"],
toteutin

2022-09-13 09:42 UTC, ValheKouneli commented on src/pages/index.tsx
> +}
toteutin

2022-09-13 09:43 UTC, ValheKouneli commented
> Pitikö tän jo hakea jotain. Tätä ei kannata mergee ennen ku toi lomake oikeesti hakee jotain. Enterillä hakeminen ei täl hetkel viel toimi. Se on kyl kans yks juttu mikä varmaa tarttettais.

Ei tämä hae hakuehdoilla, kun BE:tä ei ole vielä olemassa, ja jos yrittää lähettää sinne hakuparametreja, niin kosahtaa.

2022-09-14 09:00 UTC, tkork commented on src/components/kansalaisenEtusivu/Hakulomake.tsx
> +  );
Tohon routeriin pushattavat queryt olis kyl hyvä siivota. Nyt sinne tulee kaikki noi parametrit riippumatta onko kentät tyhjiä vai ei. Vastaavanlaista funkkaria siis vois käyttää kuin src/pages/yllapito/index.tsx:ssä oleva omitUnnecessaryFields.

2022-09-14 09:01 UTC, tkork commented on src/components/kansalaisenEtusivu/Hakulomake.tsx
> +                    />
Tähän ois hyvä lisää addEmptyOption

2022-09-14 09:03 UTC, tkork commented
Mun mielestä kaikki lomakkeen kentät olis hyvä disabloida niin kauan kunnes toi haku saadaan kuntoon. Aiheuttaa käyttäjille paljon vähemmän hämmennystä sillain.

2022-09-16 06:35 UTC, tkork approved these changes

2022-09-16 06:41 UTC, merged