feat: HASSU-710 projektin reititys aktiiviseen vaiheeseen
finnishtransportagency/hassu pull request #418
Opened 2022-10-03 13:45 UTC by kettunju

* lisaa projektin juurisivulle ja catch all -sivulle ohjaus aktiiviseen vaiheeseen

2022-10-06 06:59 UTC, ValheKouneli requested changes
Tarvitsee pari pientä muutosta. Muuten hyvä ja toimii.

2022-10-06 06:59 UTC, ValheKouneli commented on src/components/kansalaisenEtusivu/Hakutulokset.tsx
>    }
Tässä funktiossa on regressiobugi. case Status.SUUNNITTELU pitäisi olla return "suunnittelu", ei "suunnitteluvaihe".

2022-10-06 06:59 UTC, ValheKouneli commented on src/pages/suunnitelma/[oid]/index.tsx
> +        <p>{t("siirrytaan-aktiiviseen-vaiheeseen")}</p>
Jos projektia ei ole olemassa (osoiteriville annetaan joku mielivaltainen oid), niin sivulla näkyy ensin "ohjataan aktiiviseen vaiheeseen" ja sitten tyhjää, eikä esim. 404 tms.

2022-10-06 06:59 UTC, ValheKouneli commented on src/pages/suunnitelma/[oid]/index.tsx
> +    return <></>;
Olisi hyvä näyttää jotain, edes virhekoodi.

2022-10-07 06:53 UTC, kettunju commented on src/components/kansalaisenEtusivu/Hakutulokset.tsx
>    }
ei regressiobugia rebasen jälkeen

2022-10-07 07:07 UTC, kettunju commented on src/pages/suunnitelma/[oid]/index.tsx
> +    return <></>;
Lisätty virheteksti.

Yleisempi ja yhtenäistetty (?) virheiden käsittely ja näyttäminen tulossa myöhemmin

2022-10-07 07:48 UTC, kettunju commented on src/pages/suunnitelma/[oid]/index.tsx
> +        <p>{t("siirrytaan-aktiiviseen-vaiheeseen")}</p>
tähänkin lisätty nyt virheteksti, mutta varsinainen virheiden käsittely ja näyttäminen tulee omalla tiketillää koko frontille (nyt esim toi error typistetään common apissa geneeriseksi api-virheeksi)

2022-10-07 11:05 UTC, ValheKouneli approved these changes

2022-10-07 15:20 UTC, merged