feat: Kunta ja maakunta: Keywordit Velhon metadatasta
finnishtransportagency/hassu pull request #452
Opened 2022-10-19 12:15 UTC by haapamakim

2022-10-20 12:15 UTC, ValheKouneli commented
(Tämä bugi saattaa olla mainissa eikä liitty tähän branchiin)

Kansalaispuolella fyysisessä vuorovaikutustlaisuudessa on tilaisuuden paikan kohdalla "null". (Tietokannassa on "Kantolan koulu".) Virkamiespuolella näkyy oikein.
<img width="718" alt="Screenshot 2022-10-20 at 15 13 04" src="https://user-images.githubusercontent.com/2444326/196945616-64375dd1-1ac1-4886-ad1b-3ec7d8efc061.png">

2022-10-20 12:27 UTC, ValheKouneli commented
<img width="1155" alt="Screenshot 2022-10-20 at 15 25 25" src="https://user-images.githubusercontent.com/2444326/196948174-7a4e3421-7d3e-4d42-a0ba-2cfb474aa537.png">
Alertien tyylit on rikki, mutta tämä voi olla vain mun joku lokaali ongelma, joka johtuu ympäristön rikkinäisyydestä. Tsekkaa kuitenkin, että varmasti sulla toimii.

2022-10-20 12:41 UTC, ValheKouneli commented
En saa kuntia kääntymään ruotsiksi, esim. ruotsinkielisessä vuorovaikutuksen kutsussa:
<img width="601" alt="Screenshot 2022-10-20 at 15 34 04" src="https://user-images.githubusercontent.com/2444326/196951175-1872ba0c-f8b9-4bc0-b0a6-91ccc655cb02.png">

2022-10-20 12:52 UTC, ValheKouneli commented on src/pages/index.tsx
>            vaylamuoto: vaylamuoto ? [vaylamuoto] : undefined,
Nyt kansalaisen suunnitelmahaku ei palauta mitään, vaikka ei olisi rajoituksia päällä. Se johtunee tästä. Open searchiin tulee hakutermeiksi vaikka ei olisi mitään rajoituksia.

```
                    {
                        "terms": {
                            "maakunnat.keyword": [
                                0
                            ]
                        }
                    },
                    {
                        "terms": {
                            "kunnat.keyword": [
                                0
                            ]
                        }
                    }
```

2022-10-21 08:26 UTC, ValheKouneli commented
<img width="208" alt="Screenshot 2022-10-21 at 11 25 11" src="https://user-images.githubusercontent.com/2444326/197149676-d46284c0-65ab-468b-bbb7-b7a109a3bdb7.png">
Aloituskuulutuksen esikatselussa on kunnan edustajan yhteystiedoissa vielä kunnan nimi suomeksi. Muissa kohdissa kuulutusta kunnan nimi on oikein ruotsiksi.

2022-10-21 09:26 UTC, ValheKouneli commented
<img width="516" alt="Screenshot 2022-10-21 at 12 25 27" src="https://user-images.githubusercontent.com/2444326/197162629-59316b23-e212-45f9-b65a-476e4186d5c5.png">
Hyväksymispäätöksen ilmoitus kunnille ruotsinkielisessä pdf:ssä suomenkieliset kunnat.

2022-10-21 09:29 UTC, ValheKouneli requested changes
Vielä on tehtävää. Katso uudet kommenttini.

2022-10-26 12:36 UTC, tkork approved these changes
Valheen mainitsemat ongelmat korjattu. Itse en havainnut mitään lisäkorjattavia. LGTM!

2022-10-26 12:56 UTC, merged