feat: BE: aloituskuulutuksen uudelleenkuuluttaminen
finnishtransportagency/hassu pull request #463
Opened 2022-11-07 11:25 UTC by haapamakim

2022-11-11 11:50 UTC, tkork requested changes

2022-11-11 11:50 UTC, tkork commented on backend/src/handler/tila/aloitusKuulutusTilaManager.ts
> +
Funktion nimi on mielestäni aika huono. Pitäisikö eriyttää validointi ja datojen keruu projektista omiksi funktioikseen?

2022-11-11 11:50 UTC, tkork commented on backend/src/handler/tila/aloitusKuulutusTilaManager.ts
> +
Toinen vaihtoehto olisi nimetä funktio kuvaavammaksi nyt kun kerta funktiossa tehdään muutakin kuin validointia

2022-11-14 06:53 UTC, haapamakim commented on graphql/types.graphql
> +
Kyllä sen voisi. Ehkäpä erillisellä tiketillä ettei tämä paisu liikaa(?)

2022-11-14 13:55 UTC, haapamakim commented on backend/src/handler/tila/aloitusKuulutusTilaManager.ts
> +
Hyvä pointti. Muokkasin sitä nyt niin, että vastuut menevät oikein.

2022-11-15 09:31 UTC, tkork approved these changes

2022-11-15 09:31 UTC, merged