feat: Mahdollista aloituskuulutuksen uudelleenkuulutus
finnishtransportagency/hassu pull request #477
Opened 2022-11-21 08:15 UTC by tkork

2022-11-21 09:23 UTC, tkork commented
HUOM! kansalaisnäkymästä puuttuu "Uusi aineisto" -merkinnät. korjaan

2022-11-22 11:19 UTC, ValheKouneli requested changes
Hyvä hyvä. Ihan jotain pikkujuttuja vois tsekata, kuten noi muistivuotohommelit, ni ei jää niitä lojumaan. Tuli himo kattoo et onhan BE-logiikka kunnossa, mut ainaskin tää Fe on.

2022-11-22 11:19 UTC, ValheKouneli commented on src/components/projekti/aloituskuulutus/AloituskuulutusLukunakyma.tsx
> +  ensisijainenKieli: Kieli | null | undefined;
VFC on deprikoitumassa

2022-11-22 11:19 UTC, ValheKouneli commented on src/schemas/uudelleenKuulutus.ts
> +    .optional();
Pitäiskö tässä olla merkkimäärän rajoitus, kerta aloituskuulutuksen kuvaukseenkin lisättiin?

2022-11-22 11:58 UTC, tkork commented on src/schemas/uudelleenKuulutus.ts
> +    .optional();
No tätä mietin, mutta missään specseissä ei ollut mainintaa. Laitan vaikka 2000 sinne rajaks

2022-11-22 11:59 UTC, tkork commented on src/schemas/uudelleenKuulutus.ts
> +    .optional();
Kyselen, et mikä se vois olla ja ehdotan tota 2000 :tta

2022-11-23 10:03 UTC, ValheKouneli approved these changes
Good enough :) kuten sovittiin

2022-11-23 10:05 UTC, merged