feat: optimistinen lukitus projektin tallennukseen
finnishtransportagency/hassu pull request #517
Opened 2022-12-22 07:35 UTC by haapamakim

2023-01-05 13:31 UTC, tkork requested changes

2023-01-05 13:31 UTC, tkork commented on backend/src/database/palauteDatabase.ts
> +      await projektiDatabase.saveProjektiWithoutLocking({ oid: palaute.oid, uusiaPalautteita: 1 });
Tässä tätä ei oo kylläkään muutettu, mutta pitäskö tän kasvattaa tota uusiaPalautteita yhdellä sen sijaan, että asettaa sen 1:ksi?

2023-01-05 13:31 UTC, tkork commented on src/util/defaultVastaanottajat.ts
> +      delete kunta.lahetysvirhe;
Olen myös tehnyt saman korjauksen tänne ja se on nyt mainissa. Tarpeettomien kenttien deletoinnin sijaan on parempi valita tarvitut kentät.

2023-01-05 13:31 UTC, tkork commented on src/hooks/useProjekti.tsx
> +  console.log("useProjekti", projekti);
Pitäisikö poistaa console.log?

2023-01-05 13:31 UTC, tkork commented on src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
> +    console.log("tallentamisTiedot", { versio: projekti.versio });
Poistettaisko console.log?

2023-01-05 13:31 UTC, tkork commented on src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
> +      console.log("Tallenna", { formDataVersio: formData.versio });
Console.login poisto?

2023-01-05 13:31 UTC, tkork commented on src/components/projekti/paatos/aineistot/Muokkausnakyma.tsx
> +      versio: projekti.versio,
Mulla lintteri valittaa, että dependency arrayssa pitäs olla toi projekti.versio
Elikkä depsiarray vois olla vaiks 
- [julkaisematonPaatos, projekti.oid, projekti.versio]

2023-01-05 13:31 UTC, tkork commented on src/pages/yllapito/projekti/[oid]/index.tsx
> -        reset(data);
ton onSubmitin dependency arrayssa on turhaan nyt toi reset

2023-01-05 13:44 UTC, tkork commented
Ja kommenttina vielä... Eikös tän featuren mergen jälkee pidä joko lisätä versio tietoa kaikkiin projekteihin ympäristössä tai tyhjentää projektikanta

2023-01-09 11:49 UTC, haapamakim commented on backend/src/database/palauteDatabase.ts
> +      await projektiDatabase.saveProjektiWithoutLocking({ oid: palaute.oid, uusiaPalautteita: 1 });
Se on tuossa vain lippu, että uusia palautteita on. Tuota kenttää käytetään indeksissä ja niissä ei ole booleanit tuettuina.

2023-01-09 12:19 UTC, haapamakim commented on src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
> +    console.log("tallentamisTiedot", { versio: projekti.versio });
Poistettu.

2023-01-09 12:19 UTC, haapamakim commented on src/hooks/useProjekti.tsx
> +  console.log("useProjekti", projekti);
Poistettu.

2023-01-09 12:19 UTC, haapamakim commented on src/pages/yllapito/projekti/[oid]/aloituskuulutus.tsx
> +      console.log("Tallenna", { formDataVersio: formData.versio });
Poistettu.

2023-01-09 12:19 UTC, haapamakim commented on src/pages/yllapito/projekti/[oid]/index.tsx
> -        reset(data);
Poistettu.

2023-01-09 12:20 UTC, haapamakim commented
> Ja kommenttina vielä... Eikös tän featuren mergen jälkee pidä joko lisätä versio tietoa kaikkiin projekteihin ympäristössä tai tyhjentää projektikanta

Muutin conditionin sietämään puuttuvan version.

2023-01-09 12:39 UTC, tkork approved these changes

2023-01-09 12:40 UTC, merged