feat: Automaatio aineistojen kategorisoinnin lisäykseen
finnishtransportagency/hassu pull request #536
Opened 2023-01-11 08:24 UTC by tkork

2023-01-11 12:12 UTC, haapamakim approved these changes
Hyvältä näyttää!

2023-01-11 12:28 UTC, ValheKouneli requested changes
Tarvitsee lisää testejä.
Lisäksi ei toimi kuten oli tarkoitus, eli jos UI:ssa valitsee "Tuo aineistoja" Suunnitteluaineistojen alla, valitsee ison kasan tiedostoja ja klikkaa "Tuo aineistot", tällä hetkellä aineistoja menee myös muiden pääkategorioiden alle.
Jatkokehitykseen tulee mieleen useampikin tiketti, mutta jos tuon nyt korjaisi ja tekisi testit, olisi edes sisäisesti eheästi toimiva kokonaisuus.

2023-01-19 09:18 UTC, tkork commented
- Jouduin lisäilemään nyt uusia statuksia, joilla voidaan kälissä tunnistaa siirretäänkö kälissä aineistosivulle vai kuulutussivulle. 
- Samalla tuli tarpeeseen siirtää kuulutussivut uuteen polkuun, jotta navigointi saadaan toimimaan järkevästi. 
- Tietty bäkkäriin jouduin muokkaamaan projektiStatusHandleria niin, että ottaa noi uudet statukset huomioon.

2023-01-20 12:41 UTC, ValheKouneli requested changes
Kun lisäsin nähtävilläolovaiheelle aineistot, mutta en lisäaineistoja, ja sitten painoin tallenna ja siirry..., tuli Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'aineistotValmiit')
Tiedostossa src/hooks/useProjektinTila.ts rivillä 15
if (tila.aineistotValmiit) {

toi tila ei ole määritelty...

2023-01-20 12:41 UTC, ValheKouneli commented on src/components/projekti/suunnitteluvaihe/LuonnoksetJaAineistot/MuokkaustilainenLomake.tsx
> +            .map<AineistoInput>((velhoAineisto) => ({ dokumenttiOid: velhoAineisto.oid, nimi: velhoAineisto.tiedosto }));
Täältä puuttuu toi forEach((aineisto) => { value.push(aineisto) }

2023-01-23 08:28 UTC, tkork commented on src/components/projekti/suunnitteluvaihe/LuonnoksetJaAineistot/MuokkaustilainenLomake.tsx
> +            .map<AineistoInput>((velhoAineisto) => ({ dokumenttiOid: velhoAineisto.oid, nimi: velhoAineisto.tiedosto }));
Toi ylemmän kommentin havainto johtuu mainissa jo olevasta ongelmasta, ei tässä featuresta tehdyistä muutoksista. Sinne korjattiin tänään se ongelma.

Hyvä havainto tämä toinen. Korjaan, testailen vielä vähän ja rebasetan tän.

2023-01-23 12:21 UTC, ValheKouneli requested changes
Valitettavasti suunnitteluvaiheen aineistoissa on vieläkin virheitä. Jos lähtötilanne on se, että on hassu automaattitestiprojekti, ja sillä on 3 esittelyaineistoa, ja sitten valitsee jotkin 3 muuta tiedostoa suunnitelmaluonnoksiksi, niin UI:ssa näkyy kaikki oikein, mutta tallentamisen jälkeen esittelyaineistot ovat hävinneet (UI:ssa niitä ei ainakaan käy).

Myös toinen bugi tuli vastaan. Siinä oli lähtötilanteessa tiedostoja sekä esittelyaineistoissa että suunnitelmaluonnoksissa. Kun suunnitelmaluonnokset poisti ja tallensi, tallentamisen jälkeen kaikki aineistot olivat hävinneet.

2023-01-24 07:04 UTC, tkork commented
En saanut toistettua mitään mainitsemistasi ongelmista. Enkä nyt käsitä missä kohtaa olisin rikkonut suunnitteluvaiheesta noita toiminnallisuuksia. 

Jos siellä on jotain hajalla, pitäisi tarkistaa ensin onko ongelma myös mainissa. Jos on, lisätään bugitikettiä ja korjataan niillä. Jos taas ei ole, kaipaisin toisto-ohjeita ja näyttöä siitä, että minä olen hajottanut toiminnallisuudet näillä muutoksilla.

2023-01-25 11:24 UTC, ValheKouneli approved these changes
Suunnitteluvaiheen ongelmat aiheuttava bugi löytyi. Se on mainissa. Nämä muutokset ok.

2023-01-25 11:37 UTC, merged