feat: HASSU-1409 kansalaisen pudotusvalikot saavutettavuus
finnishtransportagency/hassu pull request #556
Opened 2023-01-25 09:16 UTC by kettunju

https://www.sketch.com/s/2a56e864-0b55-4ade-b294-17366a9a8a0e/a/jgYG077

2023-01-25 11:26 UTC, tkork commented on src/components/kansalaisenEtusivu/Hakulomake.tsx
> +                    .filter((option) => option.value !== "")
Pitäskö tän filtteröinnin sijaan poistaa kuntametadata.ts tiedostosta tyhjien optioneiden pushaaminen. Tän siis vois tehdä sekä kuntaOptions, että maakuntaOptions funktioihin (rivit 217 ja 229).

2023-01-25 11:27 UTC, tkork requested changes
Muuten mun mielest OK. Mut turhaan sinne kuntalistaan lisätää ensiks tyhjää ja sit filtteröidää se myöhemmin pois :)

2023-01-25 16:45 UTC, kettunju commented on src/components/kansalaisenEtusivu/Hakulomake.tsx
> +                    .filter((option) => option.value !== "")
lisätty kuntametadataan toistaiseksi tuki molemmille select-komponenteille tyhjän option kanssa ja ilman sitä

2023-01-26 09:19 UTC, tkork approved these changes

2023-01-26 11:49 UTC, merged