Feature/hassu 1423 final
finnishtransportagency/hassu pull request #616
Opened 2023-02-20 08:44 UTC by mustonenk

2023-02-22 12:57 UTC, tkork requested changes
- Generoidut tyypit olis parempia, jos logoFI-kentät olis pakollisia (huutomerkit types.graphql ja inputs.graphql)
- “Hello”-lokitukset vois joko poistaa tai tehdä kuvaavimmiks
- Backend ja Integration snapshotit pitäs päivittää
- EU-rahoitusvalintaa ei pitäisi enää sallia, jos aloituskuulutusjulkaisu on hyväksyttävänä tai hyväksytty. (Logoja-kuvien muokkaaminen on vissiin sallittavaa sen jälkeenkin). Samanlainen toteutus on Suunnittelusopimuksella.
- Käyttöliittymä on “epäsynkassa” kun logot on valittuna ja painaa Ei-radiopainiketta ja sen jälkeen Kyllä-painiketta. Samaiset logokuvat näkyvät käyttöliittymässä, mutta tallentaessa näkyy alla oleva näky.

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/77731851/220625488-928911fa-0c64-41d5-ab76-69698ab8c58a.png">

2023-02-22 12:57 UTC, tkork commented on graphql/inputs.graphql
> +  logoFI: String
LogoFI on pakollinen. Tohon vois laittaa huutomerkin perään.

2023-02-22 12:57 UTC, tkork commented on graphql/types.graphql
> +  logoFI: String
logoFI on pakollinen tohon vois laittaa huutomerkin perään.

2023-02-22 12:57 UTC, tkork commented on backend/src/database/model/projekti.ts
> +  logoFI?: string;
Voiskohan tästäkin logoFI:stä poistaa tuon optionalisuuden?

2023-02-22 12:57 UTC, tkork commented on backend/src/handler/asiakirjaHandler.ts
> +    log.info("XLoading projekti", { oid });
Ootko vahingos muokannut kommenttia? :)

2023-02-22 12:57 UTC, tkork commented on backend/src/handler/tila/aloitusKuulutusTilaManager.ts
> +    log.info("aktm ");
Tän vois siivoo pois

2023-02-27 12:29 UTC, mustonenk commented on backend/src/handler/tila/aloitusKuulutusTilaManager.ts
> +    log.info("aktm ");
Muut huomatukset korjattu,
paitsi graphql huutomerkki-kenttä ei istunut kohtuullisella työllä ratkaisuun, koska tossa lähetään tyhjää kenttää silloin kun logourl ei muutu.

2023-02-28 10:37 UTC, tkork approved these changes

2023-02-28 10:58 UTC, merged