fix: Korjaa logiikka funkkariin, joka kertoo onko ok luoda uusi vuorovaiku…
finnishtransportagency/hassu pull request #781
Opened 2023-04-26 13:22 UTC by ValheKouneli

…tus. Lisää validaattoriin kohta, joka tukee tätä logiikkaa, eli ei uusi kierros ei saa olla edellistä aiemmin.

2023-04-26 13:22 UTC, ValheKouneli commented on backend/src/projekti/adapter/projektiAdapterJulkinen.ts
>        const viimeisinVuorovaikutusKierros: VuorovaikutusKierrosJulkaisu = julkaistutVuorovaikutukset[julkaistutVuorovaikutukset.length - 1];
Tää oli tuplasti, ni otin pois

2023-04-26 13:22 UTC, ValheKouneli commented on backend/src/util/validation.ts
>    return dayjs().isAfter(lastVuorovaikutusTime);
Jos kaikki tilaisuudet on peruttu, on ok aloittaa uusi kierros

2023-04-27 09:02 UTC, tkork requested changes

2023-04-27 09:02 UTC, tkork commented on backend/src/projekti/projektiValidator.ts
> +  }
Tässä on ehkä muutenkin turhaa checkkailua kierrosnumeron kanssa. Virheellä ei ole tekemistä sen kanssa onko nbr undefined, null, 1 vai kaksi.

2023-04-28 06:08 UTC, tkork approved these changes

2023-04-28 06:08 UTC, merged