feat: Virkamiehen palautteiden parannus Hassu-1700
finnishtransportagency/hassu pull request #826
Opened 2023-05-19 11:59 UTC by mustonenk

2023-05-23 09:49 UTC, ValheKouneli requested changes
Tee testit palauteSchemaUpgradeen. Tee myös BE-testit asetaPalauteVastattu-toiminnolle. Laita ne mukaan integraatiotesteihin. Korjaa lisäksi mainitut virheet.

2023-05-23 09:49 UTC, ValheKouneli commented on src/components/projekti/suunnitteluvaihe/SaapuneetKysymyksetJaPalautteet.tsx
> +    if (vastattu) {
poista console.log

2023-05-25 05:26 UTC, mustonenk commented on backend/src/database/palauteSchemaUpdate.ts
> +
korjattu

2023-05-25 05:26 UTC, mustonenk commented on backend/src/database/palauteDatabase.ts
> +      log.info("HELLO");
korjattu

2023-05-25 05:26 UTC, mustonenk commented on common/abstractApi.ts
> +    console.log(vastattu);
korjattu

2023-05-25 05:26 UTC, mustonenk commented on src/components/projekti/suunnitteluvaihe/SaapuneetKysymyksetJaPalautteet.tsx
> +    if (vastattu) {
korjattu

2023-05-25 05:38 UTC, mustonenk commented
> Tee testit palauteSchemaUpgradeen. Tee myös BE-testit asetaPalauteVastattu-toiminnolle. Laita ne mukaan integraatiotesteihin. Korjaa lisäksi mainitut virheet.

-Lisätty migratePalauteFromOldSchema.test.ts
-asetaPalauteVastattu-toiminnolle on palaute.ts.test:issä sama testi kuin vanhalle otaKasitetllyyn:lle. Tartteeko jotain muuta?
-mainitut virheet korjattu

2023-05-30 10:31 UTC, ValheKouneli approved these changes
LGTM

2023-05-31 07:17 UTC, merged