fix: HASSU-1765 Korjaa sonar havaintoja
finnishtransportagency/hassu pull request #872
Opened 2023-07-11 09:15 UTC by tkork

2023-08-03 10:13 UTC, ValheKouneli commented on backend/integrationtest/api/api.test.ts
> +    ).to.eventually.be;
Puuttuu fulfilled?

2023-08-03 10:17 UTC, tkork commented on backend/integrationtest/api/api.test.ts
> +    ).to.eventually.be;
Juu puuttuu

2023-08-03 20:44 UTC, ValheKouneli requested changes
schemaUpdatessa on hyvä refaktorointi, mutta se ei huomioi sitä, jos vuorovaikutuksen sisällä muuttuu useampi asia, esim. vuorovaikutusTilaisuudessa pitäis sekä lisätä lokalisaatio kaikkiin kenttiin että muuttaa yhden avaimen nimeä. Laitoin viestillä testin, joka saa kiinni tuon ongelman. Vanhassa koodissa vuorovaikutusTilaisuudet käytettiin kertaalleen cloneDeepWithin läpi sen toisen cloneDeepWithin sisällä.

getAsianhallintaSynchronizationStatus-funkkarissa pohdin, pitäiskö tosta EI_TESTATTAVISSA tehdä vähintään joku const, että se ei olis vain random string.

Tosi paljon hyviä refaktorointeja. Vähän liikaa tosin erillisiä refaktorointeja yhdessä PR:ssä. Väsähdin adaptStandardiYhteystiedot:n kohdalla.

2023-08-04 05:26 UTC, tkork commented
> schemaUpdatessa on hyvä refaktorointi, mutta se ei huomioi sitä, jos vuorovaikutuksen sisällä muuttuu useampi asia, esim. vuorovaikutusTilaisuudessa pitäis sekä lisätä lokalisaatio kaikkiin kenttiin että muuttaa yhden avaimen nimeä. Laitoin viestillä testin, joka saa kiinni tuon ongelman. Vanhassa koodissa vuorovaikutusTilaisuudet käytettiin kertaalleen cloneDeepWithin läpi sen toisen cloneDeepWithin sisällä.
> 
> getAsianhallintaSynchronizationStatus-funkkarissa pohdin, pitäiskö tosta EI_TESTATTAVISSA tehdä vähintään joku const, että se ei olis vain random string.
> 
> Tosi paljon hyviä refaktorointeja. Vähän liikaa tosin erillisiä refaktorointeja yhdessä PR:ssä. Väsähdin adaptStandardiYhteystiedot:n kohdalla.

Mun pitää kattoo tota schemaUpdatea täs branchissa viel.

Samaa mieltä tosta EI_TESTATTAVISSA. Lisään sen nyt ainakin muuttujaan. Tietyl taval ymmärtää, että toi ei oo siin union tyypissä, mitä se funktion muuten palauttaa. Mikko oli kans sitä vastaan, että lisäis sen siihen uniontyyppiin, joka on peräisin siit asianhallintakoodista.

Mietin kans, et tulee varmaa liian pitkää. Pahoittelut

2023-08-08 10:10 UTC, merged