Feature/hassu 1421
finnishtransportagency/hassu pull request #885
Opened 2023-08-08 12:11 UTC by mustonenk

2023-08-09 09:47 UTC, ValheKouneli requested changes
Riippumatta siitä, miten aiemmin joku muu oli toteuttanut virheenkäsittelyä BE:ssä, en ole tyytyväinen siihen, miten se tehdään nyt.
Tässä on hyvä esimerkki toimivasta patternista: https://engineering.udacity.com/handling-errors-like-a-pro-in-typescript-d7a314ad4991

Voisi määrittää yhden HassuError-luokan, jossa myös määritellään, minkä nimisiä HassuErrorit voivat olla. Tällöin myös näkisi yhdestä tiedostosta, mitä Error-tyyppejä on toteutettu. Aina kun BE:ssä tarvii heittää error, sen voisi heittää vaan laittamalla

```
throw new HassuError({
  name: "JOKU_ANNETUISTA_NIMISTÄ",
  message: "joku viesti",
  cause: e.message
})
```

Virheiden catchaaminen pitäisi keskittää yhteen paikkaan.

Frontin puolella asiat ovat paremmalla mallilla, tosin en katsonut sitä vielä niin syvällisesti.

2023-08-15 11:49 UTC, ValheKouneli commented on src/util/errorMessageUtil.ts
> +  },
Tuo virhe voi olla muukin kuin hakuun liittyvä, esim. jos velhossa kentät on muuttuneet ja sen takia tallennus ei onnistu - eikö?

2023-08-15 11:49 UTC, ValheKouneli approved these changes
Ton yhden virheviestin voisi muuttaa, mutta muuten hyvä. Testailin myös UI:ssa feikkaamalla BE:ssä pari velho-erroria.

2023-08-15 12:01 UTC, mustonenk commented on src/util/errorMessageUtil.ts
> +  },
Joo, toi nyt oli mun huono käännös "request" -> "haku".
Olisko "Velho palautti virheen." ?

2023-08-15 12:57 UTC, merged