feat: hassu 1822 be aineistojen muokkaus kuulutuksen jalkeen
finnishtransportagency/hassu pull request #922
Opened 2023-09-05 13:55 UTC by ValheKouneli

Jotta olisi mahdollita peruuttaa aineistomuokkaus eli asettaa esim. nahtavillaoloVaihee-objektiin se kama, mikä siellä oli aiemmin, on oltava keino asettaa NahtavillaoloVaiheJulkaisussa oleva kama nahtavillaoloVaiheen sisälle. Tämä edellytti aiemmin sitä, että nahtavillaoloVaiheJulkaisun yhteystiedot olisi konvertoinut takaisin kuulutusYhteystiedoiksi, joka on muotoa StandardiYhteystiedot. Operaatio ei ole triviaali. Tämän takia kuulutusJulkaisuihin on lisätty nyt kuulutusYhteystiedot ja VuorovaikutusKierrosJulkaisuihin esitettavatYhteystiedot.

VuorovaikutusKierrosJulkaisuun on laitettu yhteystiedot pakolliseksi. Aiemmin niin ei ollut.

PR sisältää muutokset, jotka liittyvät kyseiseen tietokantamuutoksen, ja testit muutoksiin liittyen. Mm. ProjektiSchemaUpgrade ja migraatioskripti huomioivat nämä muutokset. Muutokset huomioidaan myös adaptereissa.

Projektin aineistomuokkaustoiminto on toteutettu siten, että se on normaalia projektin muokkausta. Lisäsin kuitenkin eston sille, että kuulutuksia ei voi muokata, jos niiden muokkausTila on LUKU tai MIGROITU, ja toisaalta jos tila on AINEISTO_MUOKKAUS, vain aineistoja voi muokata.

adaptMuokkausTila ottaa nyt huomioon aineistoMuokkaus-kentän ja yksi mahdollinen aineistomuokkaus-tila on AINEISTO_MUOKKAUS. Adapterin päivittämisen yhteydessä huomasin, että siitä ei ollut otettu huomioon mahdollisuutta, että migraation jälkeen olisi tehty uudelleenkuulutus, eli että olisi yksi migroitu kuulutus ja sen jälkeen normaali kuulutus. Korjasin adapterin tältä osalta.

2023-09-12 11:29 UTC, tkork requested changes

2023-09-12 11:29 UTC, tkork commented on backend/src/projekti/validator/projektiValidator.ts
> +      }
Suosittelen käyttämään tyypitystä apuna. Nyt tuolla on typoja osassa avaimissa. Lisäks __typenamea ei tuu inputissa.

esimerkki tyypitys: 
      const allowedInputKeys: (keyof NahtavillaoloVaiheInput | keyof HyvaksymisPaatosVaiheInput)[] = [
        "aineistoNahtavilla",
        "lisaAineisto",
        "nahtavillaoloSaamePDFt",
        "hyvaksymisPaatosVaiheSaamePDFt",
      ];

2023-09-12 11:32 UTC, tkork requested changes
Olin näemmä kahdelle välilehdelle tehnyt arviota. (tuli kuitenkin kommentit hienosti molemmista)

2023-09-12 12:06 UTC, ValheKouneli commented on backend/src/projekti/validator/projektiValidator.ts
> +}
Muutosta ei ole tehty, koska ei kuulunut tiketin scopeen. Hölmösti on jätetty aikanaan validoimatta koko aloituskuulutuksen muokkaus, ni en ruvennut tekemään validointia.

2023-09-13 10:54 UTC, ValheKouneli commented on graphql/types.graphql
> +  yhteystiedot: [Yhteystieto!]!
Ei sinne, koska vain soittoajoissa on yhteystiedot

2023-09-14 10:15 UTC, tkork requested changes
Voitasko kattoa tätä yhdessä niin, et katottais mistä johtuu, et meil on erilaiset eslint-valitukset?

2023-09-14 10:15 UTC, tkork commented on backend/src/projekti/validator/projektiValidator.ts
> +        (input as Record<string, any>)[key] === undefined ||
Tästä mul tulee eslint valitusta `Unexpected any. Specify a different type.`. Näihin valituksiin en ite ees oo keksinyt viel kunnon ratkaisuja. Kaiken pitäs olla kunnolla tyypitettyä, että tätä anya ei tarvis käyttää. Mut tarvitaaks tässä edes periaattees tota `input as Record<string, any>)[key] === undefined` kun onko se edes laitonta muokkaus. Ainakin virheellinen virheviesti throwaantuu tässä if-lohkossa.

2023-09-14 13:12 UTC, tkork requested changes
Katotaa yhdes toi juttu

2023-09-14 13:12 UTC, tkork commented on backend/src/handler/tila/nahtavillaoloTilaManager.ts
> +    return { ...rest, uudelleenKuulutus: null, aineistoMuokkaus: null };
Enää mielestäni tässä on ihmetystä. Onko OK, että uudelleenkuulutus asetetaan OK:ksi. Sama homma hyväksymispäätöksen tilamanagerissa.

2023-09-15 08:28 UTC, ValheKouneli commented on backend/src/handler/tila/nahtavillaoloTilaManager.ts
> +    return { ...rest, uudelleenKuulutus: null, aineistoMuokkaus: null };
Kun aineistomuokkaus perutaan, sekä aineistoMuokkaus että uudelleenKuulutus nenevät null:ksi. Jos ne olisivat muuta kuin null:ia, oltaisiin muokkaustilassa. Tässä siis palataan lähtötilaan ennen kun aineistomuokkaus on avattu.

2023-09-15 09:12 UTC, tkork commented on backend/src/handler/tila/nahtavillaoloTilaManager.ts
> +    return { ...rest, uudelleenKuulutus: null, aineistoMuokkaus: null };
Olet oikeassa.

2023-09-15 13:40 UTC, merged