feat: hae asianhallinnan tila käyttöliittymälle. Korjaa vuorovaikutuskierrosten asianhallintaeventid:n ylimääräinen uudelleengenerointi.
finnishtransportagency/hassu pull request #936
Opened 2023-09-13 12:49 UTC by haapamakim

2023-09-15 14:18 UTC, hakalap approved these changes

2023-09-15 14:18 UTC, hakalap commented on backend/src/aws/parameters.ts
> +  async getAsianhallintaLambdaArn() {
Voisi ehkä poistaa kun ei käytetä eikä tuollaista outputtia ole.

2023-09-18 05:53 UTC, haapamakim commented on backend/src/aws/parameters.ts
> +  async getAsianhallintaLambdaArn() {
totta. Toi oli joku miten aloin sitä tekemään, mutta päädyin muuhun,

2023-10-19 09:34 UTC, ValheKouneli requested changes
Lisää testi BE-validoinnista, jos ashatila ei kunnossa.
Nykyiseltä käyttäjältä pois ashatilahomma ja muualle. Projektissa toistaiseksi ok.

2023-10-25 09:50 UTC, merged