feat: hassu 1849 integraatioyhteyden aktivointikytkin BE
finnishtransportagency/hassu pull request #957
Opened 2023-10-03 10:36 UTC by ValheKouneli

2023-10-05 07:24 UTC, hakalap approved these changes

2023-10-05 10:00 UTC, hakalap requested changes
Pitäisi kutsua vielä asianHallintaServicen enqueueSynchronization metodia siinä saveAndEnqueueSynchronization funkkarissa.

2023-10-05 12:00 UTC, hakalap approved these changes

2023-10-12 06:24 UTC, tkork requested changes
Pitäisikö ashaIntegraatio kentän nimeä muuttaa asianhallintaIntegraatio:ksi? Samaa kenttää voisi myöhemmin käyttää USPA:n kanssa.

2023-10-12 09:21 UTC, tkork approved these changes

2023-10-12 09:54 UTC, merged