feat: HASSUYP-142 suunnitteluvaiheen korjaukset
finnishtransportagency/hassu pull request #979
Opened 2023-10-26 11:07 UTC by kettunju

2023-11-01 08:50 UTC, hakalap requested changes

2023-11-01 08:50 UTC, hakalap commented on src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutustilaisuusDialog/Soittoaika.tsx
> +      />
yhteystietoVirkamiehelleTekstiksi labelista rivillä 76 pitäisi poistaa käyttäjätunnus ainakin Scetchin mukaan

2023-11-01 08:50 UTC, hakalap commented on src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutustilaisuusDialog/index.tsx
Tallenna -> OK riville 357 Schetsissä. Pitäisikö Päivitä olla myös OK?

2023-11-05 17:31 UTC, kettunju commented on src/components/projekti/suunnitteluvaihe/komponentit/VuorovaikutustilaisuusDialog/index.tsx
Tallenna vaihdettu, päivitä painikkeelle löytyi oma kuva ja ei vaihdeta

2023-11-06 06:59 UTC, hakalap approved these changes

2023-11-06 08:07 UTC, merged