Feature/hassuyp 112
finnishtransportagency/hassu pull request #981
Opened 2023-10-26 11:37 UTC by mustonenk

2023-11-01 12:11 UTC, hakalap requested changes
Jatkopäätöksien hyväksynnästä tulee vielä sama sposti projektipäällikölle kuin hyväksymispäätöksen hyväksymisestä. Asiatunnus lisäksi väärin spostin otsikossa. Siinä pitäisi olla se tunnus joka annettu jatkopäätöksille. Koskee myös niitä sposteja jossa ne pdf:t.

2023-11-27 08:53 UTC, mustonenk commented on backend/src/email/emailTemplates.ts
>  Voit tarkastella projektia osoitteessa https://${"domain"}/yllapito/projekti/${"oid"}
korjattu

2023-11-27 08:53 UTC, mustonenk commented on backend/src/email/emailTemplates.ts
>  Voit tarkastella aloituskuulutusta osoitteessa {{aloituskuulutusYllapitoUrl}}
korajttu

2023-11-27 08:54 UTC, mustonenk commented on backend/src/email/emailTemplates.ts
>  Voit tarkastella kuulutusta osoitteessa {{nahtavillaoloYllapitoUrl}}
korajttu

2023-11-27 08:57 UTC, mustonenk commented
korjattu muut paitsi asianumero joka pätettiin jätää noin

2023-12-08 07:36 UTC, hakalap approved these changes

2023-12-08 10:07 UTC, merged